# Generated by Django 5.1.3 on 2024-12-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='tentativas',
            field=models.IntegerField(max_length=10),
        ),
    ]
