# Generated by Django 5.1.3 on 2024-12-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_jogo_tentativas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='tentativas',
            field=models.CharField(max_length=10),
        ),
    ]
