# Generated by Django 5.1.3 on 2024-12-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_jogo_tentativas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.jogador'),
        ),
    ]
