# Generated by Django 5.1.3 on 2024-12-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_jogo_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='nickname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
